-- INICIO 1A
-- INICIO CRIAR TABELAS

CREATE TABLE TB_LOJA ( 
    COD_LOJA NUMBER(5, 0),  
    TX_ENDERECO VARCHAR2(50),  
    TX_TELEFONE VARCHAR2(11),  
    NM_CIDADE VARCHAR2(50),  
    VL_FATURAMENTO NUMBER(7, 2) 
); 

CREATE TABLE TB_PEDIDO (
    COD_PEDIDO NUMBER(5, 0), 
    COD_LOJA NUMBER(5, 0), 
    DT_ELABORACAO DATE,       
    DT_ENTREGA DATE 
); 

CREATE TABLE TB_FORNECEDOR ( 
    COD_FORNECEDOR NUMBER(5, 0),  
    TX_CNPJ VARCHAR2(14),  
    NM_EMPRESA VARCHAR2(50),  
    NM_CIDADE VARCHAR2(50),  
    TX_TELEFONE VARCHAR(11),  
    TX_EMAIL VARCHAR(50)
); 

CREATE TABLE TB_ESTOQUE (
    COD_ESTOQUE NUMBER(5, 0),
    TX_ENDERECO VARCHAR2(50),
    NM_CIDADE VARCHAR2(50)
);

CREATE TABLE TB_PRODUTO (
    COD_PRODUTO NUMBER(5, 0),
    NM_MEDICAMENTO VARCHAR2(50),
    TX_DESCRICAO VARCHAR2(200),
    NM_COMPOSICAO VARCHAR2(60),
    NM_LAB VARCHAR2(60)
);

CREATE TABLE TB_PEDIDO_PRODUTO (
    COD_PEDIDO NUMBER(5, 0),
    COD_PRODUTO NUMBER(5, 0),
    VL_QUANTIDADE NUMBER(5, 0)
);

CREATE TABLE TB_LOJA_PRODUTO (
    COD_LOJA NUMBER(5, 0),
    COD_PRODUTO NUMBER(5, 0),
    VL_QTDE_EST_LOJA NUMBER(5, 0)
);

CREATE TABLE TB_ESTOQUE_PRODUTO (
    COD_ESTOQUE NUMBER(5, 0),
    COD_PRODUTO NUMBER(5, 0),
    VL_QUANTIDADE NUMBER(5, 0)
);

CREATE TABLE TB_ESTOQUE_FORNECEDOR (
    COD_ESTOQUE NUMBER(5, 0),
    COD_FORNECEDOR NUMBER(5, 0)
);

CREATE TABLE TB_FORNECEDOR_PRODUTO (
    COD_FORNECEDOR NUMBER(5, 0),
    COD_PRODUTO NUMBER(5, 0)
);

-- FIM CRIAR TABELAS

-- INICIO CRIANDO CONTRAINTS
-- TB_LOJA
ALTER TABLE TB_LOJA
ADD CONSTRAINT PK_LOJA PRIMARY KEY (COD_LOJA);

-- TB_PEDIDO
ALTER TABLE TB_PEDIDO
ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (COD_PEDIDO);

ALTER TABLE TB_PEDIDO
ADD CONSTRAINT FK_LOJA FOREIGN KEY (COD_LOJA)
REFERENCES TB_LOJA (COD_LOJA);

-- TB_FORNECEDOR
ALTER TABLE TB_FORNECEDOR
ADD CONSTRAINT PK_FORNECEDOR PRIMARY KEY (COD_FORNECEDOR);

-- TB_ESTOQUE
ALTER TABLE TB_ESTOQUE
ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (COD_ESTOQUE);

-- TB_PRODUTO
ALTER TABLE TB_PRODUTO
ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO);

-- TB_PEDIDO_PRODUTO
ALTER TABLE TB_PEDIDO_PRODUTO
ADD CONSTRAINT FK_PEDIDO_TB_PED_PROD FOREIGN KEY (COD_PEDIDO)
REFERENCES TB_PEDIDO (COD_PEDIDO);

ALTER TABLE TB_PEDIDO_PRODUTO
ADD CONSTRAINT FK_PRODUTO_TB_PED_PROD FOREIGN KEY (COD_PRODUTO)
REFERENCES TB_PRODUTO (COD_PRODUTO);

ALTER TABLE TB_PEDIDO_PRODUTO
ADD CONSTRAINT PK_PEDIDO_PRODUTO
PRIMARY KEY (COD_PEDIDO, COD_PRODUTO);

-- TB_LOJA_PRODUTO
ALTER TABLE TB_LOJA_PRODUTO
ADD CONSTRAINT FK_LOJA_TB_LOJA_PROD FOREIGN KEY (COD_LOJA)
REFERENCES TB_LOJA (COD_LOJA);

ALTER TABLE TB_LOJA_PRODUTO
ADD CONSTRAINT FK_PRODUTO_TB_LOJA_PROD FOREIGN KEY (COD_PRODUTO)
REFERENCES TB_PRODUTO (COD_PRODUTO);

ALTER TABLE TB_LOJA_PRODUTO
ADD CONSTRAINT PK_LOJA_PRODUTO
PRIMARY KEY (COD_LOJA, COD_PRODUTO);

-- TB_ESTOQUE_PRODUTO
ALTER TABLE TB_ESTOQUE_PRODUTO
ADD CONSTRAINT FK_EST_TB_EST_PROD FOREIGN KEY (COD_ESTOQUE)
REFERENCES TB_ESTOQUE (COD_ESTOQUE);

ALTER TABLE TB_ESTOQUE_PRODUTO
ADD CONSTRAINT FK_PROD_TB_EST_PROD FOREIGN KEY (COD_PRODUTO)
REFERENCES TB_PRODUTO (COD_PRODUTO);

ALTER TABLE TB_ESTOQUE_PRODUTO
ADD CONSTRAINT PK_ESTOQUE_PRODUTO
PRIMARY KEY (COD_ESTOQUE, COD_PRODUTO);

-- TB_ESTOQUE_FORNECEDOR
ALTER TABLE TB_ESTOQUE_FORNECEDOR
ADD CONSTRAINT FK_EST_TB_EST_FORN FOREIGN KEY (COD_ESTOQUE)
REFERENCES TB_ESTOQUE (COD_ESTOQUE);

ALTER TABLE TB_ESTOQUE_FORNECEDOR
ADD CONSTRAINT FK_FORN_TB_EST_FORN FOREIGN KEY (COD_FORNECEDOR)
REFERENCES TB_FORNECEDOR (COD_FORNECEDOR);

ALTER TABLE TB_ESTOQUE_FORNECEDOR
ADD CONSTRAINT PK_ESTOQUE_FORNECEDOR
PRIMARY KEY (COD_ESTOQUE, COD_FORNECEDOR);

-- TB_FORNECEDOR_PRODUTO
ALTER TABLE TB_FORNECEDOR_PRODUTO
ADD CONSTRAINT FK_FORN_TB_FORN_PROD FOREIGN KEY (COD_FORNECEDOR)
REFERENCES TB_FORNECEDOR (COD_FORNECEDOR);

ALTER TABLE TB_FORNECEDOR_PRODUTO
ADD CONSTRAINT FK_PROD_TB_FORN_PROD FOREIGN KEY (COD_PRODUTO)
REFERENCES TB_PRODUTO (COD_PRODUTO);

ALTER TABLE TB_FORNECEDOR_PRODUTO
ADD CONSTRAINT PK_FORNECEDOR_PRODUTO
PRIMARY KEY (COD_FORNECEDOR, COD_PRODUTO);
-- FIM CRIANDO CONTRAINTS
-- FIM 1A
